import type { Product, Category, Coupon, SiteSettings, Order } from "@/types";

const now = () => new Date().toISOString();

/**
 * Seed data uses local /assets paths by default. Once you upload images to
 * Supabase via the admin panel, products will use the Supabase public URLs.
 */
export const SEED_SETTINGS: SiteSettings = {
  storeName: "FENIX",
  tagline: "Style Meets Versatility",
  supportEmail: "support@fenix.store",
  supportPhone: "+880 1XXXXXXXXX",
  supportWhatsapp: "+880 1XXXXXXXXX",
  currency: "BDT",
  lowStockThreshold: 5,
  shippingDhaka: 80,
  shippingOther: 140,
  bkashNumber: "01XXXXXXXXX",
  paymentInstructions:
    "Send the exact order total to the bKash number above using the 'Send Money' option. After paying, return to your order and submit your Transaction ID, sender number, and the amount paid.",
  footerNote:
    "Premium custom jerseys and streetwear-inspired sports pieces, built for everyday wear and standout drops.",
  announcement: "Premium sportswear drops · free-tier optimized · full admin workflow",
  featuredKicker: "Featured products",
  featuredTitle: "Best-selling jerseys and standout drops",
  featuredCopy:
    "Every featured card links to a dedicated product page with multiple images, sizes, stock status, discount logic, and related products.",
  categoriesKicker: "Categories",
  categoriesTitle: "Shop by Collection",
  categoriesCopy: "Browse by product type to jump straight into your preferred collection.",
  newsletterTitle: "Join the drop list",
  newsletterCopy:
    "Get restock alerts, new arrivals, and exclusive release updates directly in your inbox.",
  aboutTitle: "About FENIX",
  aboutBody:
    "FENIX is a premium custom jersey label blending football heritage with everyday streetwear. Every piece is designed to feel bold, wearable, and instantly giftable — engineered for fans who want sportswear with more personality.",
  contactTitle: "Contact us",
  contactBody:
    "Questions about sizing, orders, or custom drops? Reach our team and we'll get back to you within one business day.",
  policiesTitle: "Policies",
  policiesBody:
    "Returns accepted within 7 days for unworn items with tags. Delivery in 2-4 business days inside Dhaka and 3-6 days nationwide. Payment is verified manually before processing.",
  heroBanner: {
    eyebrow: "Custom jersey store",
    title: "Elevated football fits for everyday rotation",
    copy: "Discover limited custom jerseys, collector-style drops, and premium essentials built for fans who want sportswear with more personality.",
    primaryLabel: "Shop the collection",
    primaryLink: "/shop",
    secondaryLabel: "Explore featured drops",
    secondaryLink: "/shop?sort=featured",
    image: "/assets/hero-bg.jpg",
    productImage: "/assets/hero-product.png",
  },
};

export const SEED_CATEGORIES: Category[] = [
  { id: "cat-jerseys", name: "Custom Jerseys", slug: "jerseys", description: "Bold football-inspired custom pieces and collector drops.", image: "/assets/banner-card-1.jpg", enabled: true, order: 1 },
  { id: "cat-tees", name: "Premium Tees", slug: "premium-tees", description: "Everyday essentials with elevated prints and cleaner styling.", image: "/assets/banner-card-2.jpg", enabled: true, order: 2 },
  { id: "cat-art", name: "Graphic Tees", slug: "graphic-tees", description: "Statement tees with a softer premium finish and modern silhouettes.", image: "/assets/banner-card-3.jpg", enabled: true, order: 3 },
  { id: "cat-bottoms", name: "Bottoms", slug: "bottoms", description: "Minimal athletic bottoms made for movement and easy styling.", image: "/assets/promo-wide.jpg", enabled: true, order: 4 },
];

export const SEED_COUPONS: Coupon[] = [
  { id: "coupon-1", code: "FENIX10", type: "percent", value: 10, minOrder: 1200, enabled: true },
  { id: "coupon-2", code: "DROP150", type: "fixed", value: 150, minOrder: 2000, enabled: true },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod-noir-championship",
    name: "Fenix Noir Championship Jersey",
    categoryId: "cat-jerseys",
    category: "Custom Jerseys",
    description: "A signature dark-base Fenix jersey with electric blue ornamental patterning and premium collector appeal.",
    details: "Built for fans who want a dramatic statement piece, this jersey combines a bold match-inspired fit with clean shoulder detailing and a fashion-first custom finish.",
    specifications: ["Performance-inspired lightweight fabric", "Comfortable regular fit", "Collector-style crest placement", "Ideal for casual wear and gifting"],
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    stock: 12,
    sku: "FNX-JSY-001",
    originalPrice: 1750,
    offerPrice: 1399,
    mainImage: "/assets/products/product-5-main.jpg",
    detailImages: ["/assets/products/product-5-detail-1.jpg", "/assets/products/product-5-detail-2.jpg", "/assets/products/product-5-detail-3.jpg"],
    featured: true,
    newArrival: true,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-brazil-solar",
    name: "Brazil Solar Home Jersey",
    categoryId: "cat-jerseys",
    category: "Custom Jerseys",
    description: "A vibrant yellow football jersey with premium crest detailing and comfortable everyday wearability.",
    details: "This piece blends strong match-day character with a relaxed fit and a breathable feel that works well beyond the stadium.",
    specifications: ["Soft sportswear finish", "Regular fit silhouette", "Bright contrast trim", "Easy to pair with denim or track pants"],
    sizeOptions: ["S", "M", "L", "XL"],
    stock: 9,
    sku: "FNX-JSY-002",
    originalPrice: 1500,
    offerPrice: 1199,
    mainImage: "/assets/products/product-1-main.jpg",
    detailImages: ["/assets/products/product-1-detail-1.jpg", "/assets/products/product-1-detail-2.jpg", "/assets/products/product-1-detail-3.jpg"],
    featured: true,
    newArrival: false,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-argentina-sky",
    name: "Argentina Sky Legacy Jersey",
    categoryId: "cat-jerseys",
    category: "Custom Jerseys",
    description: "Classic sky-blue stripes, gold-inspired badge detailing, and a timeless football silhouette.",
    details: "A clean collector look with an easy fit and iconic visual balance, ideal for fans who prefer refined football styling.",
    specifications: ["Collector-inspired striping", "Premium trim finish", "Comfortable fit", "Lightweight and soft"],
    sizeOptions: ["M", "L", "XL", "XXL"],
    stock: 6,
    sku: "FNX-JSY-003",
    originalPrice: 1600,
    offerPrice: 1299,
    mainImage: "/assets/products/product-2-main.jpg",
    detailImages: ["/assets/products/product-2-detail-1.jpg", "/assets/products/product-2-detail-2.jpg", "/assets/products/product-2-detail-3.jpg"],
    featured: true,
    newArrival: true,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-spain-ivory",
    name: "Spain Ivory Heritage Jersey",
    categoryId: "cat-jerseys",
    category: "Custom Jerseys",
    description: "A more understated collector jersey with soft ivory tones and deep heritage-inspired accents.",
    details: "Designed for customers who want football influence with a cleaner, elevated feel. Works beautifully with neutral styling.",
    specifications: ["Soft textured look", "Retro-inspired finish", "Regular fit", "Premium statement trim"],
    sizeOptions: ["S", "M", "L", "XL"],
    stock: 14,
    sku: "FNX-JSY-004",
    originalPrice: 1550,
    offerPrice: 1349,
    mainImage: "/assets/products/product-3-main.jpg",
    detailImages: ["/assets/products/product-3-detail-1.jpg", "/assets/products/product-3-detail-2.jpg", "/assets/products/product-3-detail-3.jpg"],
    featured: false,
    newArrival: false,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-brazil-night",
    name: "Brazil Night Strike Jersey",
    categoryId: "cat-jerseys",
    category: "Custom Jerseys",
    description: "A dark and energetic Brazil concept jersey with electric accents and limited-drop attitude.",
    details: "Great for customers who want more contrast and mood. It feels bold, graphic, and intentionally styled for streetwear rotation.",
    specifications: ["Night-mode graphic look", "Collector-inspired silhouette", "Soft performance hand feel", "Limited-drop aesthetic"],
    sizeOptions: ["M", "L", "XL"],
    stock: 4,
    sku: "FNX-JSY-005",
    originalPrice: 1650,
    offerPrice: 1249,
    mainImage: "/assets/products/product-4-main.jpg",
    detailImages: ["/assets/products/product-4-detail-1.jpg", "/assets/products/product-4-detail-2.jpg", "/assets/products/product-4-detail-3.jpg"],
    featured: true,
    newArrival: false,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-cyberpunk-tee",
    name: "Cyberpunk Studio Tee",
    categoryId: "cat-tees",
    category: "Premium Tees",
    description: "A relaxed black graphic tee designed for easy everyday styling and premium off-field comfort.",
    details: "An oversized feel with strong front graphic impact, made for pairing with trousers, cargos, or layered sportswear looks.",
    specifications: ["Soft cotton-rich feel", "Relaxed silhouette", "Clean screen graphic", "Easy styling essential"],
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    stock: 15,
    sku: "FNX-TEE-001",
    originalPrice: 950,
    offerPrice: 799,
    mainImage: "/assets/products/product-6-main.jpg",
    detailImages: ["/assets/products/product-6-detail-1.jpg", "/assets/products/product-6-detail-2.jpg", "/assets/products/product-6-detail-3.jpg"],
    featured: false,
    newArrival: true,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-motion-track-pants",
    name: "Motion Track Pants",
    categoryId: "cat-bottoms",
    category: "Bottoms",
    description: "A streamlined black athletic bottom with tapered structure and versatile daily wear appeal.",
    details: "This essential bottom works with jerseys, tees, and outerwear. It is built for movement but styled for everyday rotation.",
    specifications: ["Tapered athletic fit", "Lightweight fabric", "Minimal styling", "Comfort waist design"],
    sizeOptions: ["M", "L", "XL", "XXL"],
    stock: 8,
    sku: "FNX-BTM-001",
    originalPrice: 1200,
    offerPrice: 999,
    mainImage: "/assets/products/product-7-main.jpg",
    detailImages: ["/assets/products/product-7-detail-1.jpg", "/assets/products/product-7-detail-2.jpg", "/assets/products/product-7-detail-3.jpg"],
    featured: false,
    newArrival: false,
    enabled: true,
    createdAt: now(),
  },
  {
    id: "prod-workofart-tee",
    name: "Work of Art Tee",
    categoryId: "cat-art",
    category: "Graphic Tees",
    description: "A soft white premium tee with artistic print placement and a bright, versatile everyday look.",
    details: "A clean statement tee that feels equally at home with casual fits and more styled sportswear layering.",
    specifications: ["Soft premium fabric", "Relaxed fit", "Statement front artwork", "Designed for daily wear"],
    sizeOptions: ["S", "M", "L", "XL"],
    stock: 11,
    sku: "FNX-TEE-002",
    originalPrice: 1100,
    offerPrice: 899,
    mainImage: "/assets/products/product-8-main.jpg",
    detailImages: ["/assets/products/product-8-detail-1.jpg", "/assets/products/product-8-detail-2.jpg", "/assets/products/product-8-detail-3.jpg"],
    featured: true,
    newArrival: false,
    enabled: true,
    createdAt: now(),
  },
];

export const SEED_ORDERS: Order[] = [];
